/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ar.com.conversor.pantallas;

import ar.com.conversor.modelo.Monedas;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Federico Moresi
 */
public class ConversorMonedas extends javax.swing.JFrame {

	/**
	 * Creates new form PantallaInicial
	 */
	public ConversorMonedas() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		cboMonedaIngresada = new javax.swing.JComboBox<>();
		jLabel1 = new javax.swing.JLabel();
		spnEdad = new javax.swing.JSpinner();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		cboMonedaRetornada = new javax.swing.JComboBox<>();
		btnConvertir = new javax.swing.JButton();
		btnSalir = new javax.swing.JButton();
		lblResultado = new javax.swing.JLabel();
		btnLimpiar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Conversor de monedas");

		cboMonedaIngresada.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "Dolar", "Euro", "Peso Argentino", "Peso Mexicano", "Real" }));
		cboMonedaIngresada.setSelectedIndex(2);

		jLabel1.setText("Ingrese la cantidad de dinero a convertir");

		spnEdad.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

		jLabel2.setText("Seleccione el tipo de moneda ingresado");

		jLabel3.setText("Seleccione el tipo de cambio que desea");

		cboMonedaRetornada.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "Dolar", "Euro", "Peso Argentino", "Peso Mexicano", "Real" }));

		btnConvertir.setText("Convertir");
		btnConvertir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnConvertirActionPerformed(evt);
			}
		});

		btnSalir.setText("Salir");
		btnSalir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSalirActionPerformed(evt);
			}
		});

		lblResultado.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
		lblResultado.setForeground(new java.awt.Color(204, 0, 51));
		lblResultado.setToolTipText("");

		btnLimpiar.setText("Limpiar");
		btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnLimpiarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup()
												.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
														.createSequentialGroup()
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel1).addComponent(jLabel2)
																.addComponent(jLabel3))
														.addGap(37, 37, 37)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																.addComponent(spnEdad)
																.addComponent(cboMonedaIngresada, 0,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		cboMonedaRetornada,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 127,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
														.createSequentialGroup().addComponent(btnConvertir)
														.addGap(31, 31, 31)
														.addComponent(btnLimpiar,
																javax.swing.GroupLayout.PREFERRED_SIZE, 79,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(35, 35, 35)
														.addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE,
																79, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(30, 30, 30)))))
						.addGap(67, 67, 67)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(34, 34, 34)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
						.addComponent(spnEdad, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(cboMonedaIngresada, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel2))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3)
						.addComponent(cboMonedaRetornada, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(26, 26, 26)
				.addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(33, 33, 33)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap(33, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {
		double cantidadIngresada = (double) spnEdad.getValue();
		double monedaIngresada;
		double monedaRetornada;

		Monedas monedas = new Monedas();

		String listaDeMonedas[] = monedas.monedas;
		Map<String, Double> mapaDeMonedas = new HashMap();

		for (int i = 0; i < listaDeMonedas.length; i++) {
			mapaDeMonedas.put(listaDeMonedas[i], monedas.getDolar());

		}

		mapaDeMonedas.put("Dolar", monedas.getDolar());
		mapaDeMonedas.put("Euro", monedas.getEuro());
		mapaDeMonedas.put("Peso Argentino", monedas.getPesoArgentino());
		mapaDeMonedas.put("Peso Mexicano", monedas.getPesoMexicano());
		mapaDeMonedas.put("Real", monedas.getReal());

		monedaIngresada = mapaDeMonedas.get(cboMonedaIngresada.getSelectedItem());
		monedaRetornada = mapaDeMonedas.get(cboMonedaRetornada.getSelectedItem());

		double resultado = Math.round((cantidadIngresada / monedaIngresada * monedaRetornada) * 100d) / 100d;

		this.lblResultado.setText(
				"El resultado de la conversión a " + cboMonedaRetornada.getSelectedItem() + " es: " + resultado);
	}

	private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {

		this.dispose();
	}

	private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {
		this.spnEdad.setValue(0);
		this.cboMonedaIngresada.setSelectedIndex(2);
		this.cboMonedaRetornada.setSelectedIndex(0);
		this.lblResultado.setText("");
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ConversorMonedas().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnConvertir;
	private javax.swing.JButton btnLimpiar;
	private javax.swing.JButton btnSalir;
	private javax.swing.JComboBox<String> cboMonedaIngresada;
	private javax.swing.JComboBox<String> cboMonedaRetornada;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel lblResultado;
	private javax.swing.JSpinner spnEdad;
	// End of variables declaration
}
